### ISSUE TITLE
doesn't work with 1.18 exp snapshots

### ISSUE THREAD

**Issue by linuzzx** [Plagiatus/mc-version-compare#1]

**Comment by Plagiatus** [comment]
You are absolutely right, as it checks with the official releases and doesn't allow versions that don't fall into that scheme ([Compare.vue, L. 160](https://github.com/Plagiatus/mc-version-compare/blob/main/src/renderer/components/Compare.vue#L160)). And the experimental snapshots are not part of the official versions.

It might be an idea for a feature to disable version check and allow you to compare anything you put into the versions folder, but atm this is not supported.

**Comment by Plagiatus** [comment]
fixed in [release 0.0.3](https://github.com/Plagiatus/mc-version-compare/releases/tag/0.0.3)
